# Generated by Django 5.0.14 on 2026-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_amenity_apartment_amenities_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if no uploaded image)', max_length=500),
        ),
    ]
